// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
WHERE is_active = true
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (notes)
VALUES ($1)
RETURNING id, created_at, updated_at, is_active, notes
`

func (q *Queries) CreateItem(ctx context.Context, notes []byte) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, notes)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, created_at, updated_at, is_active, notes FROM items
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, created_at, updated_at, is_active, notes FROM items
WHERE is_active = true
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE items
SET is_active = false, updated_at = now()
WHERE id = $1 AND is_active = true
`

func (q *Queries) SoftDeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteItem, id)
	return err
}
